# Atencao: Usar como imagem base mysql:5.5
FROM mysql:5.5

# Nao e' necessario mudar nada aqui
ENV MYSQL_DATABASE crud_flask
ENV MYSQL_USER dev
ENV MYSQL_PASSWORD dev
ENV MYSQL_RANDOM_ROOT_PASSWORD yes

#Nao e' necessario atualizar nada aqui
COPY database/ /docker-entrypoint-initdb.d/
